In [1]:
%run "C:\Users\Андрей\Desktop\Хакатон\recover_and_merge_dxa_labels.py"

====================================================================================================
СКАНИРОВАНИЕ ИСХОДНЫХ DICOM
====================================================================================================
Папка: C:\Users\Андрей\Desktop\Хакатон\Исследования
Найдено *.dcm: 499
Чтение оригиналов: 403/499

C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.08110703091310150605090907130304'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.07020303111406071106010615130206'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.03030811151201151502050615010000'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.06000812101106141213041404150112'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.04131215000514000414051510091103'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.06140010030611061314081200121305'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.06000805130607060714150602050114'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.05040708141011140110131207130812'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.09050515110402090102050206010406'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.09040712010609120601031410140610'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.07120303070106110214090814060908'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.06111207031100151513000412070105'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.07140808121311040315101301051200'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.02060902040212120608040605100100'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.00150800070710000601130003010101'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.03030413031313090107050002151508'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.07150612000412081110110102150004'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.08010006000103071201020606001302'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.07000215121313030213041009101409'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.03081500040505121009070211080902'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.01140903011212140408111315130511'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.05091110020805070808081311010412'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.02060214150705060904080407131009'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.07001207050006000600091513060701'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.02150001030902110114090106081007'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.06050309100102041203101101110913'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.01081208070113050704060608151002'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.08120904010605130814050710080508'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.00071307071102020311080215100104'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.07010502020008121005080211011503'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.02090908130314030815090205060103'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.03090510061307040702090411010105'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.00011402030913150507081413120310'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.07121414121104070401050315140813'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.01021511080002000006040601030906'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.06110201011504150103041213130110'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.08110803080105090710150006100300'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.08101400121500101415120401040211'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.05110008101209050614020515000101'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.03150400010605060115070904121304'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.02081303020303061507000314011215'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.00111415140915030904140513150113'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.08111114040702130902010708100700'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.09060814101015050208090100150206'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.04051301070809101001111312060114'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.08050414010100010110100910070904'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.09001101031503060803041311070312'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.01010713081306120510130101121412'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.05150512091506110304120408070606'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.02101009080308000015051512140806'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.00101409100812000205071213151011'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.07091105080407061114081111060515'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.02091106060004131215091000000909'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.03040807040905131500140112021404'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.09071502150602001009041214040315'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.07010103100307150507061113030803'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.04131510070001011107040403071102'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.04120502090713030002100002030500'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.01091403020812111514040306051201'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.

Чтение оригиналов: 499/499

Оригинальных DICOM: 499
Уникальных SOPInstanceUID: 499
OK: ожидаемое число 499

Размеченные: физических *.dcm = 499
  DICOM: 470/499

C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.00080112010710030607090609070409'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.01080011050715071510151108031409'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.06120002061108140400041203121102'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.05010011080903070300131415001403'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.09010705011309010307011213150407'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.05101415070003100803120514081507'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.07090609050707040704081509101500'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.02141512030209141106060309030501'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.02060612071110031306070811070605'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.08001013010106001102020015031109'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.09040806151211060704090912150608'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.05140704131104071313121101000313'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.04030803131507080109070101120910'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.08080707141115140509110700030200'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.09020610121102091006070609000414'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.09141210051000000105030213061514'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.08061203141300041506070501101310'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.01080203060404010906011511140504'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.02020610071014010106090300080911'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.00041503151008120109091101041101'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.03121103130007121510030803050514'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.07070904150315000704031208001011'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.09030700121011131209150303151015'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.02000306061002040514101500000812'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.01130904120915050401031210031001'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.02120204101515130306021007150210'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.06061007030610120805010913100711'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.05111003151314100612100700031506'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.04091012040015061107090014081504'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.02060903061507111201080601150903'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.09100506150509030310111310041309'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.02080414020805070003121215081311'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.05030701101012140702110704000714'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.05001409080504151204111500000514'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.08110803070615141513021414111001'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.00030605020706130003080307080701'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.07150610130411050211021514011106'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.06080100090802110008000311010501'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.03010404051000131408111209140108'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.02031401091510001200041308031003'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.07120809010109050202061111011110'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.07081506021006111207090213090701'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.06001210040802120801060507001509'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.02030504060005060505040905021305'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.06130007090800051113070612071205'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.02060605151213121009151302130207'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.07101010011513020401030213080905'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.05111111030105140803060510040613'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.02091011000006010704070004091411'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.08151215001015040112061102060812'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.03111115071204110106020413091215'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.08021214010408050013070405100802'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.01011407000709010910090115010000'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.00121200081108110912041503010000'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.00031305050707070014000611130907'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.09110310111109140609041514031010'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.03041015000108071402071509131313'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.07150604010711031305090702140107'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.
  warn_and_log(msg)
C:\Users\Андрей\AppData\Roaming\Python\Python311\site-packages\pydicom\valuerep.py:440: UserWarning: Invalid value for VR UI: '1.2.643.5.1.13.13.12.2.77.8252.06151311061015011100110511080701'. Please see <https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_6.2-1> for allowed values for each VR.

  DICOM: 499/499

Размеченные_244_Илья: физических *.dcm = 244
  DICOM: 244/244

Размеченные_499_Илья: физических *.dcm = 499
  DICOM: 499/499

Размеченные_old: физических *.dcm = 3
  DICOM: 3/3


====================================================================================================
СТАТИСТИКА ПО ИСТОЧНИКАМ
====================================================================================================
              source  folder_exists  physical_dicom_count  labels_csv_rows  csv_rows_resolved  csv_rows_unresolved  unique_annotated_uids  LEG  SPINE  UNKNOWN  internal_conflicts
         Размеченные           True                   499              499                499                    0                    499  331    165        3                   1
Размеченные_244_Илья           True                   244              244                244                    0                    244  164     80        0                   0
Размеченные_499_Илья           True                   499              499                499                    0                    499  333    166        0                   0
     Размеченные_old           True                     3                3                  3                    0                      3    0      0        3                   0


====================================================================================================
ПОПАРНЫЕ ПЕРЕСЕЧЕНИЯ
====================================================================================================
            source_1             source_2  n_1  n_2  intersection  only_1  only_2  union  jaccard
         Размеченные Размеченные_244_Илья  499  244           244     255       0    499 0.488978
         Размеченные Размеченные_499_Илья  499  499           499       0       0    499 1.000000
         Размеченные      Размеченные_old  499    3             3     496       0    499 0.006012
Размеченные_244_Илья Размеченные_499_Илья  244  499           244       0     255    499 0.488978
Размеченные_244_Илья      Размеченные_old  244    3             0     244       3    247 0.000000
Размеченные_499_Илья      Размеченные_old  499    3             3     496       0    499 0.006012


Всего уникальных DICOM с какой-либо разметкой: 499
DICOM, размеченных во всех непустых источниках: 0


====================================================================================================
СОГЛАСОВАННОСТЬ
====================================================================================================
status
AGREE               493
KNOWN_VS_UNKNOWN      6

LEG ↔ SPINE конфликтов: 0


====================================================================================================
MASTER LABELS
====================================================================================================
label
LEG      333
SPINE    166

Всего уникальных размеченных SOP UID: 499
Готово для LEG/SPINE обучения: 499
Требуют ручного пересмотра: 0


====================================================================================================
ГОТОВО
====================================================================================================
Отчёты сохранены в:
C:\Users\Андрей\Desktop\Хакатон\labels_recovery_report

Главный файл для прототипа:
C:\Users\Андрей\Desktop\Хакатон\labels_recovery_report\10_labels_master_LEG_SPINE.csv

Конфликты для ручной проверки:
C:\Users\Андрей\Desktop\Хакатон\labels_recovery_report\08_hard_conflicts_LEG_vs_SPINE.csv

In [2]:
source_annotations_df[
    [
        "source",
        "canonical_relative_path",
        "csv_label",
        "private_label",
        "internal_conflict",
    ]
].head(30)

,source,canonical_relative_path,csv_label,private_label,internal_conflict
0,Размеченные,2.25.156375884487675936513403083218009333856/s...,LEG,LEG,False
1,Размеченные,2.25.181196659018348153828200695057897449628/s...,LEG,LEG,False
2,Размеченные,2.25.39068163399801173920284179500049527111/se...,LEG,LEG,False
3,Размеченные,2.25.73070100851377917031356937075051545239/se...,LEG,LEG,False
4,Размеченные,2.25.307021710202910067378603383388989711646/s...,SPINE,SPINE,False
5,Размеченные,2.25.215177279960644564778148238928738915103/s...,LEG,LEG,False
6,Размеченные,2.25.164566280810634620154538016595892212884/s...,LEG,LEG,False
7,Размеченные,2.25.105033841136787477881326326053319223817/s...,SPINE,SPINE,False
8,Размеченные,2.25.276415754443998872860614500027519740375/s...,SPINE,SPINE,False
9,Размеченные,2.25.13325817932854000792938662637654885530/se...,LEG,LEG,False
10,Размеченные,2.25.186201010600484120326273381077449377115/s...,LEG,LEG,False
11,Размеченные,2.25.181196659018348153828200695057897449628/s...,LEG,LEG,False
12,Размеченные,2.25.114887542067602662452692698814728642117/s...,LEG,LEG,False
13,Размеченные,2.25.16773626720107440979805052259711419763/se...,LEG,LEG,False
14,Размеченные,2.25.66397484472966116002950503539482860450/se...,SPINE,SPINE,False
15,Размеченные,2.25.129239680100193368599713239115902740628/s...,LEG,LEG,False
16,Размеченные,2.25.177745077805190810016231350557005569203/s...,LEG,LEG,False
17,Размеченные,2.25.177745077805190810016231350557005569203/s...,LEG,LEG,False
18,Размеченные,2.25.116822802042655971810859435524105064465/s...,LEG,LEG,False
19,Размеченные,2.25.272690031744216183651627058502316132741/s...,LEG,LEG,False
20,Размеченные,2.25.66397484472966116002950503539482860450/se...,SPINE,SPINE,False
21,Размеченные,2.25.156021661584944120526934974594604520993/s...,LEG,LEG,False
22,Размеченные,2.25.91981043841368764114007975581101713077/se...,SPINE,SPINE,False
23,Размеченные,2.25.157462338378550185821790046400986801350/s...,LEG,LEG,False
24,Размеченные,2.25.157462338378550185821790046400986801350/s...,LEG,LEG,False
25,Размеченные,2.25.186201010600484120326273381077449377115/s...,LEG,LEG,False
26,Размеченные,2.25.127126130998341190348103034690069487890/s...,LEG,LEG,False
27,Размеченные,2.25.276415754443998872860614500027519740375/s...,LEG,LEG,False
28,Размеченные,2.25.307021710202910067378603383388989711646/s...,LEG,LEG,False
29,Размеченные,2.25.156375884487675936513403083218009333856/s...,SPINE,SPINE,False

In [3]:
(
    source_annotations_df
    .groupby(
        [
            "csv_label",
            "private_label",
        ]
    )
    .size()
    .reset_index(name="count")
    .sort_values(
        "count",
        ascending=False
    )
)

  csv_label private_label  count
0       LEG           LEG    827
2     SPINE         SPINE    411
3   UNKNOWN       UNKNOWN      6
1       LEG       UNKNOWN      1

In [4]:
source_annotations_df[
    source_annotations_df[
        "internal_conflict"
    ]
][
    [
        "source",
        "canonical_relative_path",
        "sop_uid",
        "csv_label",
        "private_label",
        "annotator",
        "annotated_at",
    ]
]

,source,canonical_relative_path,sop_uid,csv_label,private_label,annotator,annotated_at
381,Размеченные,2.25.126293418391331346694592071563510265596/s...,1.2.643.5.1.13.13.12.2.77.8252.111513041014020...,LEG,UNKNOWN,,2026-09-16T16:36:41

In [5]:
conflict_uids = (
    source_annotations_df.loc[
        source_annotations_df[
            "internal_conflict"
        ],
        "sop_uid"
    ]
    .unique()
)

source_annotations_df[
    source_annotations_df[
        "sop_uid"
    ].isin(conflict_uids)
][
    [
        "source",
        "canonical_relative_path",
        "sop_uid",
        "label",
        "csv_label",
        "private_label",
        "annotator",
        "annotated_at",
    ]
].sort_values(
    [
        "sop_uid",
        "source",
    ]
)

,source,canonical_relative_path,sop_uid,label,csv_label,private_label,annotator,annotated_at
381,Размеченные,2.25.126293418391331346694592071563510265596/s...,1.2.643.5.1.13.13.12.2.77.8252.111513041014020...,LEG,LEG,UNKNOWN,,2026-09-16T16:36:41
1124,Размеченные_499_Илья,2.25.126293418391331346694592071563510265596/s...,1.2.643.5.1.13.13.12.2.77.8252.111513041014020...,LEG,LEG,LEG,,2026-09-16T17:57:47